server:
  port: 8082

spring:
  main:
    allow-circular-references: true
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # for blue path, redirect to blue-server
        - id: blue                     # name of the server
          uri: lb://blue-server        # location of the server
          predicates:
            - Path=/blue/**            # if path containes
#          filters:
#            - name: RedirectFilter     # filter as per last updated app

        # for green path, redirect to green-server
        - id: green                    # name of the server
          uri: lb://green-server       # location of the server
          predicates:
            - Path=/green/**           # if path containes
#          filters:
#            - name: RedirectFilter     # filter as per last updated app
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# make appear whenever a new update is pushed to green, through lb://blue-server we can get the updated Green Version
# and the vice-versa
